stages:
  - module-pipelines

argocd:
  stage: module-pipelines
  trigger:
    include:
      #- "/kubernetes/.gitlab-ci.yml"
      - "/argocd/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      #- kubernetes/**/*
      - argocd/**/*
