---
apiVersion: networking.k8s.io/v1
# ingress controller
kind: Ingress
metadata:
  name: frontend
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - "{{ .Values.fqdn }}"
  rules:
    - host: "{{ .Values.fqdn }}"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: {{ .Values.service.port }}