---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-report-hpa
  labels:
    app: backend-report-hpa
spec:
  minReplicas: {{ .Values.spec.minReplicas }}
  maxReplicas: {{ .Values.spec.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-report
  targetCPUUtilizationPercentage: {{ .Values.spec.targetCPUUtilizationPercentage }}
