---
apiVersion: v1
kind: Service
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: backend-report