image: gitlab.praktikum-services.ru:5050/russianvoodoo4/sausage-store/sausage-backend
tag: latest
imagePullPolicy: IfNotPresent
replicas: 1
service:
  port: 8080
vault:
  port: 8200
  host: 130.193.51.105
resources:
  requests:
    memory: "1024Mi"
    cpu: "200m"
  limits:
    memory: "2048Mi"
    cpu: "500m" 
containerPolicies:
  minAllowed:
    cpu: 0m
    memory: 0Mi
  maxAllowed:
    cpu: 500m
    memory: 2048Mi