---
- name: Один плей для запуска backend сервиса сосисочной
  # Шаблон целевых хостов это группа хостов с именем backend
  hosts: backend
  # Список ansible-ролей для backend-серверов
  roles:
    - backend
  become: yes
  gather_facts: no

- name: Второй плей для запуска frontend сервиса сосисочной
  # Шаблон целевых хостов это группа хостов с именем frontend
  hosts: frontend
  # Список ansible-ролей для frontend-серверов
  roles:
    - frontend
  become: yes
  gather_facts: no
