---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: backend
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: backend
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: {{ .Values.containerPolicies.minAllowed.cpu }}
          memory: {{ .Values.containerPolicies.minAllowed.memory }}
        maxAllowed:
          cpu: {{ .Values.containerPolicies.maxAllowed.cpu }}
          memory: {{ .Values.containerPolicies.maxAllowed.memory }}
        controlledResources: ["cpu", "memory"]
        controlledValues: RequestsAndLimits